import '../styles/globals.css';
import { Montserrat } from 'next/font/google';

const monteserrat = Montserrat({ subsets: ['latin'] });

export const metadata = {
  title: 'Formula One Clone',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={monteserrat.className}>{children}</body>
    </html>
  );
}
